# Basic
name:               "CATS Lab @KAIST"
title:              "CATS Lab (Computational Analytics of Technology and Society) at the Korea Advanced Institute of Science and Technology"
description:        "CATS Lab is a research group at the Korea Advanced Institute of Science and Technology that connects people interested in applying data science to social problems."


# URL
url:                https://catslab.kaist.ac.kr/
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "about"
    href:           "/about"
  - name:           "news"
    href:           "/news"
  - name:           "publications"
    href:           "/publication"
  - name:           "lab meetings"
    href:           "/presentation"
  - name:           "talks"
    href:           "/talks"
  - name:           "people"
    href:           "/people"
  - name:           "matjip"
    href:           "/matjip"
# - name:           "abstracts"
#   href:           "/abstracts"
# - name:           "lab teachings"
#   href:           "/resources"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
